### ISSUE TITLE
 Could not pass event PlayerJoinEvent

### ISSUE THREAD

**Issue by Danila767** [en0tuk/eHideTags#9]
Could not pass event PlayerJoinEvent to eHideTags v1.7.2
java.lang.NullPointerException: Cannot invoke "org.bukkit.scoreboard.Team.addEntry(String)" because "ru.enis.ehidetags.misc.other.team" is null
        at ru.enis.ehidetags.misc.other.hideName(other.java:16) ~[eHideTags-1.7.2.jar:?]
        at ru.enis.ehidetags.events.onJoin.join(onJoin.java:32) ~[eHideTags-1.7.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor243.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-35]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:372) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$0(PlayerList.java:309) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1363) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1340) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1333) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1311) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1199) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by en0tuk** [comment]
How to reproduce this

**Comment by en0tuk** [comment]
Try latest build from Actions

**Comment by en0tuk** [comment]
> Try latest build from Actions

[Link](https://github.com/en0tuk/eHideTags/suites/8413347166/artifacts/372195807)
